# fly.toml app configuration file generated for blackjack-zmj6uw on 2025-07-22T13:02:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blackjack-zmj6uw'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 22
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
