FROM alpine:latest

RUN apk add --no-cache python3 openssh-server

RUN ssh-keygen -A && \
    mkdir -p /run/sshd

COPY blackjack.py /root/blackjack.py
RUN chmod +x /root/blackjack.py

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    echo "PermitEmptyPasswords yes" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "ForceCommand /usr/bin/python3 /root/blackjack.py" >> /etc/ssh/sshd_config && \
    echo "ClientAliveInterval 30" >> /etc/ssh/sshd_config && \
    echo "ClientAliveCountMax 3" >> /etc/ssh/sshd_config && \
    passwd -d root

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e", "-p", "22"]
