app = "cyberjack-ssh"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[[services]]
  internal_port = 2222
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1  # Keep at least one running for now

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 2222

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
