app = ""
primary_region = "ord"

[[services]]
  internal_port = 22
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

  [[services.ports]]
    port = 22

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
